name: parking_booking
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  lottie: ^3.1.0
  http_parser: ^4.0.2
  razorpay_flutter: ^1.3.9
  pdf: ^3.11.3
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  intl: ^0.18.1
  image_picker: ^1.1.2
  provider: ^6.1.0
  http: ^1.3.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  socket_io_client: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/success.json
    - assets/lottie/main_car.json
    - assets/lottie/parking_animation.json
    - assets/car.svg
